-- concat_ws is only immutable on text arguments: https://stackoverflow.com/a/54384767
create or replace function immutable_concat_ws(text, variadic text[])
returns text as 'select array_to_string($2, $1)' language sql immutable parallel safe;

create table account (
    account_id bigint generated by default as identity primary key,
    version bigint not null,
    create_time timestamptz not null,
    update_time timestamptz not null
);

create table vehicle (
    account_id bigint not null,
    vehicle_id bigint generated by default as identity unique,
    version bigint not null,
    create_time timestamptz not null,
    update_time timestamptz not null,
    display_name text,
    primary key (account_id, vehicle_id),
    foreign key (account_id) references account (account_id)
);
